---
title: "diq3"
author: "Subharthi"
date: "February 4, 2019"
output: rmarkdown::github_document
---

```{r setup, echo = FALSE}
knitr::opts_chunk$set(
  fig.path = "README_figs/README-"
)
```
## R Markdown



```{r}
# first set working directory 

lib.need = c("plyr", "rgdal", "maptools", "ggplot2", "rgeos", "RColorBrewer", 
             "stringr", "xtable", "scales", "foreign", "lubridate", "ggmap",
             "sp", "spatstat", "openxlsx", "gpclib", "PBSmapping", "lattice", 
             "Grid2Polygons", "RColorBrewer", "gstat",
             "KernSmooth", "MASS", "splancs", "spacetime", "plyr", "raster", "inlmisc")
new.packages <- lib.need[!(lib.need %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

lapply(lib.need, require, character.only=T)  # load needed library
setwd("C:\\Users\\developer\\Documents\\nij_realtime_crime_forecasting")
getwd()
source("NIJ-funcs.R") # function files



# load from the shape file 
# and read spatial geometry data

crime.portland.shape = readOGR(dsn=path.expand("./maps/portland-police-districts"), 
                               layer = "Portland_Police_Districts")

crime.dbf = read.dbf('./maps/portland-police-districts/Portland_Police_Districts.dbf')

# load from the shape file 
# and read spatial geometry data


origProj <- crime.portland.shape@proj4string ## Store original projection

PortlandBoundaryPolygon <- NIJ.getShapeBoundaryPolygon('./maps/portland-police-districts/Portland_Police_Districts.shp', origProj)

#Getting polygon area
PortlandBoundaryPolygonArea <- NIJ.getPolygonArea(PortlandBoundaryPolygon)

# area of POrtland in square miles
PortlandBoundaryPolygonArea$area * 3.58700658032258e-08 # mi^2 
# length


cell.length = sqrt(NIJ.convSqMi2SqFt(0.25)) #sqrt(.25) * 5280
cell.width = sqrt(NIJ.convSqMi2SqFt(0.75)) #sqrt(.75) * 5280
# width  
SpatialPortlandGrid <- NIJ.createCellGrid(crime.portland.shape, cell.length,cell.width
                                          ,origProj)
PortlandBoundaryPolygonGridded <- NIJ.createGriddedBoundaryPolygon(crime.portland.shape, SpatialPortlandGrid)


# handle crime data for notebook

data.2012 = read.xlsx ("./data/2012/NIJ2012_MAR01_DEC31.xlsx", sheet = 1, colNames=T)
```

## Including Plots

You can also embed plots, for example:

```{r plots2, echo=FALSE}


spplot(SpatialPortlandGrid, "id", colorkey=FALSE, 
       col.regions=topo.colors(seq(0,1,.01)),
       panel = function(...) {
         panel.gridplot(..., border="black")
         sp.polygons(PortlandBoundaryPolygonGridded)
         #sp.points(poi, cex=1.5)  
         
         panel.text(..., cex=0.4, col="red")
       })

# just get the cell ids
cell.ids = getSpPPolygonsIDSlots(PortlandBoundaryPolygonGridded)




crime.portland.shape@data$id = rownames(crime.portland.shape@data)

city_pl_df <- fortify(crime.portland.shape, region='id')

Pl.df = fortify(PortlandBoundaryPolygonGridded, region='id')
summary(data.2012)


# change characters to levels and check those levels
data.2012$CATEGORY = as.factor(data.2012$CATEGORY)
levels(data.2012$CATEGORY)
data.2012$CALL.GROUPS = as.factor(data.2012$CALL.GROUPS)
levels(data.2012$CALL.GROUPS)
data.2012$final_case_type = as.factor(data.2012$final_case_type)
levels(data.2012$final_case_type)
data.2012$CASE.DESC = as.factor(data.2012$CASE.DESC)
levels(data.2012$CASE.DESC)
portland.burglary.subset = subset(data.2012, (CATEGORY=="BURGLARY"))


# sort the burglary data by occurance date
portland.burglary.subset = portland.burglary.subset[order(portland.burglary.subset$occ_date), ]
summary(portland.burglary.subset)
maxLat = 740000
minLat = 640000

maxLon = 7702000
minLon = 7600000

portland.burglary.coord = portland.burglary.subset[, c("x_coordinate", "y_coordinate")]

p <-bound_plot +
    geom_point(data=portland.burglary.subset,
               aes(x=x_coordinate, y=y_coordinate, group=1), shape='x'
               , color="blue", alpha='0.8')+
  
    geom_density2d(data = portland.burglary.subset, 
                   aes(x = x_coordinate, y = y_coordinate, group=1), size = 0.3,
                   alpha = '0.3')+
        stat_density2d(data=portland.burglary.subset,
                       aes(x=x_coordinate, y=y_coordinate,group=1, 
                           fill = ..level.., alpha = ..level..), size = 0.01, 
                       bins = 24, geom = "polygon") +
    scale_fill_gradient(low = "green", high = "red") + 
    scale_alpha(range = c(0, 0.3), guide = T)

p



```
```{r plots3, echo=FALSE}


burglary.poly.IDs = NIJ.findCellIDS(portland.burglary.subset$x_coordinate, 
                                    portland.burglary.subset$y_coordinate,
                                    origProj, PortlandBoundaryPolygonGridded)
portland.burglary.subset$cell.ids = burglary.poly.IDs
pl.burg.derived =portland.burglary.subset[, c("cell.ids", "occ_date")]
pl.burg.derived$occ_date = as.Date(pl.burg.derived$occ_date, 
                                   origin='1899-12-30')
pl.burg.derived$week = (format(pl.burg.derived$occ_date,
                              format="%U"))

pl.bur.derived = ddply(pl.burg.derived, .(week, cell.ids), nrow)
#pl.bur.derived=na.omit(pl.bur.derived)
pl.bur.derived$week = (as.Date(paste(2012, pl.bur.derived$week,
                               1, sep="-"), "%Y-%U-%u"))
pl.bur.derived = pl.bur.derived[, c(2, 1,3)]
## draw a histogram with week as numbers
## will get a very similar number of crime pattern


yrs = seq(as.Date('2012-02-27'),as.Date('2012-12-31'),by = 7)
time = as.POSIXct(yrs, tz = "PST")
derived.data = expand.grid(cell.ids=cell.ids,week=yrs)
derived.data$V1 = 0 # make default crime numbers = 0


# then appoint appropriate crime numbers
#total= ddply(merge(derived.data, pl.bur.derived,by=c("cell.ids", "week"),
#                   all.x=TRUE), 
#      .(cell.ids, week), summarise, V1=sum(V1))
total = merge(derived.data, pl.bur.derived, by=c("cell.ids", "week"),
              all=T)
total <- transform(total, V1 = rowSums(total[, 3:4], na.rm = TRUE))

derived.data = total[, c("cell.ids", "week", "V1")]
summary(derived.data)
derived.data=na.omit(derived.data)
rm("total")

## just a replacement for NA
#derived.data$cell.ids[is.na(derived.data$cell.ids)] = "[7.62e+06,7.69e+06] X471"
pl.st = STFDF(PortlandBoundaryPolygonGridded, time, 
              derived.data[order(derived.data[2], derived.data[1]),])

## use this plot to see weekly hotspots



stplot(pl.st[,,"V1"], yrs)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
